server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: mall-admin #路由的ID
          uri: lb://mall-admin #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/mall-admin/**
          filters:
            - StripPrefix=1
    sentinel:
      transport:
        dashboard: localhost:9094
      datasource:
        - nacos:
            server-addr: 192.168.43.211:8848
            data-id: mall-gateway-sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
  redis:
    host: 192.168.43.211
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 300
        # 连接池中的最大空闲连接
        max-idle: 16
        # 连接池中的最小空闲连接
        min-idle: 8


