server:
  port: 9091
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: 123456
      max-active: 100 #最大连接数
      initial-size: 1  #初始化大小
      max-wait: 60000
      min-idle: 1  #最小连接数
      time-between-eviction-runs-millis: 60000  #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  #一个连接在池中最小生存的时间，单位是毫秒
  redis:
    host: 192.168.43.211
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 300
        # 连接池中的最大空闲连接
        max-idle: 16
        # 连接池中的最小空闲连接
        min-idle: 8
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mall.admin.enerty.db
feign:
  sentinel:
    enabled: true
resttemplate:
  sentinel:
    enabled: true

